edit Jenkinsfile

diff --git a/CI/Jenkinsfile b/CI/Jenkinsfile
--- a/CI/Jenkinsfile
+++ b/CI/Jenkinsfile
@@ -33,11 +33,7 @@ pipeline {
             steps {
                 dir('CI-CD-pipeline-Lab-1') {
                     sh '''
-                        #!/bin/bash
-                        source /home/dolmachi/miniconda3/etc/profile.d/conda.sh
-                        conda activate mlops
-                        dvc pull
-                        pytest --cov=src
+                        bash -c "source /home/dolmachi/miniconda3/etc/profile.d/conda.sh && conda activate mlops && dvc pull && pytest --cov=src"
                     '''
                 }
             }
@@ -56,9 +52,7 @@ pipeline {
                         sh 'cd CI-CD-pipeline-Lab-1 && docker compose build'
                     } finally {
                         sh '''
-                            #!/bin/bash
-                            cd CI-CD-pipeline-Lab-1
-                            docker compose up -d
+                            bash -c "cd CI-CD-pipeline-Lab-1 && docker compose up -d"
                         '''
                     }
                 }
@@ -69,13 +63,7 @@ pipeline {
             steps {
                 dir("CI-CD-pipeline-Lab-1") {
                     sh '''
-                        #!/bin/bash
-                        container_id=$(docker ps -qf "name=api_container")
-                        if [ -z "$container_id" ]; then
-                            echo "No container running"
-                            exit 1
-                        fi
-                        docker logs --tail 1000 "$container_id"
+                        bash -c 'container_id=$(docker ps -qf "name=api_container"); if [ -z "$container_id" ]; then echo "No container running"; exit 1; fi; docker logs --tail 1000 "$container_id"'
                     '''
                 }
             }
@@ -84,13 +72,7 @@ pipeline {
         stage('Push Docker Image to DockerHub') {
             steps {
                 sh '''
-                    #!/bin/bash
-                    image_id=$(docker images -q travissscottt/api_car_price:latest)
-                    if [ -z "$image_id" ]; then
-                        echo "Error: Docker image not found. Build might have failed."
-                        exit 1
-                    fi
-                    docker push travissscottt/api_car_price:latest
+                    bash -c 'image_id=$(docker images -q travissscottt/api_car_price:latest); if [ -z "$image_id" ]; then echo "Error: Docker image not found. Build might have failed."; exit 1; fi; docker push travissscottt/api_car_price:latest'
                 '''
             }
         }
@@ -99,13 +81,10 @@ pipeline {
     post {
         always {
             sh '''
-                #!/bin/bash
-                docker stop api_container || true
-                docker rm api_container || true
-                docker rmi travissscottt/api_car_price:latest || true
-                docker logout || true
+                bash -c "docker stop api_container || true; docker rm api_container || true; docker rmi travissscottt/api_car_price:latest || true; docker logout || true"
             '''
             cleanWs()
         }
     }
 }
+
